version: '3.7'

services:

    redis:
        image: redis:6-alpine
        container_name: redis_cont
        volumes : 
            - ./volumes/redis/data:/data
        env_file: 
            - ./.env/dev/.env.redis.dev
        ports: 
            - 6379:6379
        networks: 
            - back
        # restart: on-failure

    flask:
        build:
            context: ./services/flask
            dockerfile: Dockerfile
        image: flask:v0.8.0
        container_name: flask_cont
        volumes:
            - ./services/flask:/app
        env_file:
            - ./.env/dev/.env.flask.dev
        # expose: 
        #     - 5000
        ports:
            - 5000:5000
        networks: 
            - front
            - back
        depends_on:
            - redis
        # command: flask run
        # restart: on-failure

    nginx:
        build: 
            context: ./services/nginx
            dockerfile: Dockerfile
        image: nginx_img:0.0.0
        container_name: nginx_cont
        env_file:
            - ./.env/dev/.env.nginx.dev
        ports:
            - 1337:80
        networks: 
            - front
        depends_on:
            - flask
        # restart: always

networks: 
    front:
    back: