version: '3.3'

services:
    redis:
        image: redis
    web:
        build:
            context: .
            dockerfile: Dockerfile

        # restart always
        image: web:v0.6.0
        container_name: web_cont
        volumes:
            - .:/app
        ports: 
            - 65000:65000
        depends_on:
            - redis
