version: '3.3'

services:
    redis:
        image: redis
        ports: 
            - 6379:6379
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        # restart : always
        image: theDarwinProjectFlaskImg:v0.7.0
        container_name: flask
        volumes:
            - .:/app
        ports: 
            - 65000:65000
        depends_on:
            - redis
