version: '3.3'

services:
    redis:
        image: redis
    web:
        build:
            context: .
            dockerfile: Dockerfile
            # args:
            #     dummy: "dummy"
        # restart always
        image: web:v0.5.0
        container_name: web_cont
        volumes:
            - .:/app
        # environment:
        #     TEST_MODE: 0
        #     LOG_IN_FILE: 0
        #     LOG_LEVEL : "INFO"
        ports: 
            - 65000:65000
        depends_on:
            - redis
