version: '3.3'

services:
    redis:
        image: redis:6-alpine
        container_name: redis_cont
        ports: 
            - 6379:6379
        networks: 
            - net
    web:
        build:
            context: .
            dockerfile: Dockerfile
        # restart always
        image: web:v0.7.0
        container_name: web_cont
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
        volumes:
            - .:/app
        ports: 
            - 65000:65000
        depends_on:
            - redis
        networks: 
            - net

networks: 
    net: